Update lavalink-without-ssl.md
DarrenOfficial/lavalink-list pull request #540
Opened 2024-08-09 14:18 UTC by wsael

added Node 

### Hosted by @ [Reedroux LLC](https://reedroux-bot.xyz)
Version x4 ・ [Uptime](https://hetrixtools.com/report/uptime/1341fe35b50a625623770fcbc35cd486/) ・
```bash
Host : free.reedroux-bot.xyz
Port : 25988
Password : "reedrouxfreenode"
Secure : false
```

2024-08-09 14:19 UTC, dawgcodes commented
@DarrenOfficial pls add thanks

2024-08-09 14:29 UTC, AjieDev requested changes
did you mean `Version 4.x`

2024-08-09 14:56 UTC, dawgcodes commented
yes

2024-08-09 21:04 UTC, AjieDev commented
HTTP ERROR 502
Details: Bad Gateway | Connection refused

2024-08-10 13:58 UTC, AjieDev commented
Duplicate #543

2024-08-10 13:58 UTC, closed without merging